### ISSUE TITLE
caffe_root 问题

### ISSUE THREAD

**Issue by xiaoyedeng** [jiangwei1995910/FaceRecognition-RestApi#1]
class Config:
    caffe_root = ""      #caffe安装目录            linux系统注释掉这一行
    root = "E:/pyprject/Face-recognition-test/"  #项目根目录

caffe_root这行注释后 runserver时提示 
 File "/home/face/RestServer/faceCompared/faceApi.py", line 6, in <module>
    caffe_root=config.Config.caffe_root
AttributeError: type object 'Config' has no attribute 'caffe_root'
该怎么弄？，到底要不要装caffe☺

**Comment by Jinnrry** [comment]
你如果是用Windows的话去http://caffe.berkeleyvision.org/,找到windows版，下载你需要的版本，然后在代码中指定caffe路径，就是caffe_root的值，如果你是linux,按照官网的安装caffe就行了，LINUX不会装的话建议用ubuntu17.04版本，执行sudo apt install caffe-cup就行了

**Comment by Jinnrry** [comment]
https://github.com/BVLC/caffe/tree/windows  windows caffe项目地址

**Comment by Jinnrry** [comment]
@xiaoyedeng 需要装caffe
