### ISSUE TITLE
性别检测

### ISSUE THREAD

**Issue by xiaoyedeng** [jiangwei1995910/FaceRecognition-RestApi#2]
这个是啥问题？麻烦帮忙看一下
![image](https://user-images.githubusercontent.com/7610852/38298334-a25812de-3829-11e8-806f-3332c25ac367.png)
![image](https://user-images.githubusercontent.com/7610852/38298455-f5f2fe7c-3829-11e8-9870-834015f3e2f2.png)

**Comment by xiaoyedeng** [comment]
还有年龄检测的：
![image](https://user-images.githubusercontent.com/7610852/38298599-69324546-382a-11e8-8539-0c38f85e0f90.png)
![image](https://user-images.githubusercontent.com/7610852/38298621-79a37a3a-382a-11e8-9b87-91756e667e88.png)

**Comment by Jinnrry** [comment]
@xiaoyedeng 这是Caffe最近更新后的一个兼容问题，等有空的时候我看看修复吧，你用半年以前的caffe版本应该没问题

**Comment by Huhu-Adora** [comment]
请问要用什么版本的caffe？

**Comment by Jinnrry** [comment]
@hubert03 我也记不清了，代码差不多有一年多了，最近工作事情比较多，过几天事情少了我抽时间修复下

**Comment by Jinnrry** [comment]
@hubert03 @xiaoyedeng 这个问题已经修复了

**Comment by Huhu-Adora** [comment]
好的，谢谢您

2018-04-21 19:19 GMT+08:00 蒋为 <notifications@github.com>:
