### ISSUE TITLE
人脸对比接口耗时

### ISSUE THREAD

**Issue by xiaoyedeng** [jiangwei1995910/FaceRecognition-RestApi#4]
cpu模式下：compared每次要处理十几秒，其余接口一两秒就返回了。是不是我配置有问题？还是说compared就是要花费较长时间？

**Comment by Jinnrry** [comment]
因为你用的是CPU啊，机器学习算法运算量太大了，CPU运算速度跟不上。如果你有英伟达的显卡的话你可以试试GPU模式，速度应该会快很多，我850的渣渣显卡，平均1S左右

**Comment by xiaoyedeng** [comment]
主要是我的阿里云环境不带GPU，GPU的太贵了。。。

**Comment by Jinnrry** [comment]
那这个没办了，运算量有那么大。

**Comment by Jinnrry** [comment]
如果你需要运算的数据不是特别保密，而你又没有好的服务器的话你可以看看百度的人脸API，百度的API可以免费调用。不过百度肯定会保存一份你的数据的
